# Generated by Django 4.2.7 on 2026-02-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drawings/', verbose_name='PDF File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/', verbose_name='Processed Image')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Extracted Dimensions')),
            ],
            options={
                'verbose_name': 'Uploaded Drawing',
                'verbose_name_plural': 'Uploaded Drawings',
                'db_table': 'uploaded_drawings',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
